import '../generated/l10n.dart';
List<String> commonDishesListEN = [
  'Caesar Salad',
  'Borsch',
  'Steak',
  'Sushi',
  'Pizza',
  'Carbonara Pasta',
  'Greek Salad',
  'Sushi Rolls',
  'Chicken Kiev',
  'Meatballs',
  'Cream Soup',
  'Greek Salad',
  'Shish Kebab',
  'Lasagna',
  'French Fries',
  'Olivier Salad',
  'Harcho Soup',
  'Seafood',
  'Country-style Potatoes',
  'Aspic',
  'Grilled Chicken',
  'Dumplings',
  'Chicken Wings',
  'Shrimp Salad',
  'Khachapuri',
  'Minestrone',
  'Okroshka',
  'Niçoise Salad',
  'Taco',
  'Garlic Shrimp',
];
List<String> commonDishesListRU = [
  'Цезарь салат',
  'Борщ',
  'Стейк',
  'Суши',
  'Пицца',
  'Паста Карбонара',
  'Греческий салат',
  'Роллы суши',
  'Курица по-киевски',
  'Фрикадельки',
  'Сливочный суп',
  'Греческий салат',
  'Шашлык',
  'Лазанья',
  'Картофель фри',
  'Оливье',
  'Суп харчо',
  'Морепродукты',
  'Картофель по-деревенски',
  'Холодец',
  'Курица гриль',
  'Пельмени',
  'Куриные крылья',
  'Салат с креветками',
  'Хачапури',
  'Минестроне',
  'Окрошка',
  'Салат Ницца',
  'Тако',
  'Креветки с чесноком',
];

List<String> commonDishesListUA = [
'Цезарський салат',
'Борщ',
'Стейк',
'Суші',
'Піца',
'Паста Карбонара',
'Грецький салат',
'Роли суші',
'Курка по-київськи',
'Фрікадельки',
'З кремом суп',
'Грецький салат',
'Шашлик',
'Лазанья',
'Картопля фрі',
'Олів\'є',
'Суп харчо',
'Морепродукти',
'Картопля по-селянськи',
'Холодець',
'Курка гриль',
'Пельмені',
'Курячі крила',
'Салат з креветками',
'Хачапурі',
'Мінестроне',
'Окрошка',
'Салат Ніцца',
'Тако',
'Креветки з часником',
];


//List<String> Dishes = S.of(context).local=="ru"? commonDishesListRU:commonDishesListEN;
